package resources;

import java.io.Serializable;

public enum Queries implements Serializable{
REGISTER,
LOGIN,
SEND_MESSAGE,
GET_MESSAGE,
SEND_CHAT_ROOM_MESSAGE,
GET_CHATROOM_LIST,
CREATE_NEW_CHAT_ROOM,
GET_CHAT_ROOM_MESSAGES,
ADD_FRIEND,
UPDATE_PROFILE,
LOGOUT,
SERVER_REPLY,
HAVE_NEW_CHAT_ROOM_MESSAGE,
HAVE_NEW_FRIEND_MESSAGE,
REFRESH,
GET_FRIEND_LIST,
REQUEST_FRIEND,
GET_FRIEND_REQUST_LIST
;
}

